//! The immutable template an `Agent` hands to the loop. Shared behind an `Arc` so cloning an agent does not duplicate its tool registry or sub-agent tree.

use std::collections::HashMap;
use std::time::Duration;

use serde_json::Value;

use crate::provider::model::Model;
use crate::tools::ToolRegistry;

use crate::output::OutputSchema;

use super::agent::Agent;
use super::prompts;

/// The agent's definition. Shared across clones via `Arc<AgentSpec>` with copy-on-write
/// on builder mutations, then passed to `run_loop` directly.
///
/// `name` is eagerly generated by `Agent::new()` and overwritten by `.name(...)`.
/// `model: None` at template level means "inherit from parent"; after `Agent::compile`
/// it is always `Some` (use `AgentSpec::model()` to unwrap).
#[derive(Clone)]
pub(crate) struct AgentSpec {
    pub name: String,
    pub model: Option<Model>,
    pub identity_prompt: String,
    pub behavior_prompt: String,
    pub context_prompt: String,
    pub tool_registry: ToolRegistry,
    pub sub_agents: Vec<Agent>,
    pub output_schema: Option<OutputSchema>,
    pub max_request_tokens: Option<u32>,
    pub max_input_tokens: Option<u64>,
    pub max_output_tokens: Option<u64>,
    pub max_turns: Option<u32>,
    pub max_schema_retries: Option<u32>,
    pub max_request_retries: u32,
    pub request_retry_delay: Duration,
    pub keep_alive: bool,
}

impl Default for AgentSpec {
    fn default() -> Self {
        Self {
            name: crate::util::generate_agent_name("agent"),
            model: None,
            identity_prompt: String::new(),
            behavior_prompt: prompts::DEFAULT_BEHAVIOR_PROMPT.to_string(),
            context_prompt: String::new(),
            tool_registry: ToolRegistry::new(),
            sub_agents: Vec::new(),
            output_schema: None,
            max_request_tokens: None,
            max_input_tokens: None,
            max_output_tokens: None,
            max_turns: None,
            max_schema_retries: Some(10),
            max_request_retries: AgentSpec::DEFAULT_MAX_REQUEST_RETRIES,
            request_retry_delay: AgentSpec::DEFAULT_REQUEST_RETRY_DELAY,
            keep_alive: false,
        }
    }
}

impl AgentSpec {
    /// Default number of retries for transient API errors. Re-exported as
    /// `Agent::DEFAULT_MAX_REQUEST_RETRIES` for the public API surface.
    pub const DEFAULT_MAX_REQUEST_RETRIES: u32 = 10;

    /// Default base delay for the exponential-backoff retry policy.
    /// Re-exported as `Agent::DEFAULT_REQUEST_RETRY_DELAY`.
    pub const DEFAULT_REQUEST_RETRY_DELAY: Duration = Duration::from_millis(500);

    /// Read the resolved model. Panics if called on an unresolved spec — only
    /// `Agent::compile` is supposed to observe a spec whose model is `None`.
    pub(crate) fn model(&self) -> &Model {
        self.model
            .as_ref()
            .expect("AgentSpec::model() called on unresolved spec; Agent::compile must run first")
    }

    /// Build the provider's `system` field from `identity_prompt` (with `vars`
    /// interpolated), `behavior_prompt`, and a JSON-output directive when
    /// `output_schema` is set.
    pub(crate) fn system_prompt(&self, vars: &HashMap<String, Value>) -> String {
        let mut s = Self::interpolate(&self.identity_prompt, vars);
        if !self.behavior_prompt.is_empty() {
            s.push_str("\n\n");
            s.push_str(&self.behavior_prompt);
        }
        if self.output_schema.is_some() {
            s.push_str(prompts::STRUCTURED_OUTPUT_INSTRUCTION);
        }
        s
    }

    /// Build the first user message's context prefix: the runtime's
    /// `environment` block (when present) followed by the user-supplied
    /// `context_prompt` field. Returns `None` when both are empty so the
    /// caller can skip pushing a message altogether.
    pub(crate) fn context_prompt(&self, environment: Option<&str>) -> Option<String> {
        let mut parts: Vec<&str> = Vec::new();
        if let Some(env) = environment {
            parts.push(env);
        }
        if !self.context_prompt.is_empty() {
            parts.push(&self.context_prompt);
        }
        if parts.is_empty() {
            None
        } else {
            Some(parts.join("\n\n"))
        }
    }

    /// Replace `{key}` placeholders in `template` with stringified values.
    pub(crate) fn interpolate(template: &str, vars: &HashMap<String, Value>) -> String {
        let mut result = template.to_string();
        for (key, value) in vars {
            let replacement = match value {
                Value::String(s) => s.clone(),
                other => other.to_string(),
            };
            result = result.replace(&format!("{{{key}}}"), &replacement);
        }
        result
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn context_prompt_appended_after_environment() {
        let block = "<context>\nuser-provided context\n</context>";
        let mut spec = AgentSpec::default();
        spec.context_prompt = block.to_string();
        let ctx = spec
            .context_prompt(Some("<environment>\ntest environment\n</environment>"))
            .expect("context_prompt should be composed");

        let env_pos = ctx.find("<environment>").expect("environment missing");
        let user_pos = ctx.find(block).expect("context_prompt missing");
        assert!(
            env_pos < user_pos,
            "environment should appear before context_prompt:\n{ctx}"
        );
    }
}
